spring:
  application:
    name: app-doc-sach
  datasource:
    url: jdbc:mysql://localhost:3306/appdocsach?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: appdocsach
    password: password
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 558750477314-gsp55lnnjuj7ki5qint3epkr7p8s5dlj.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          github:
            client-id: Iv1.99344991fefa2587
            client-secret: 9cb9852fe6202faffbe10e785e88e1a6fa6b8fa9
      
# Cố định port
server:
  port: 8080

# Ghi log đẹp hơn
logging:
  charset:
    console: UTF-8
  pattern:
    dateformat: yy-MM-dd HH:mm

# cấu hình JWT
application:
  jwt:
    secret: randomStringToMakeSecretKeyFdsksdnkzvk2oejaofcjewfr4ieoru39wjfmsfddshgvndkjfnakhdhiaukrfhqiauyh98atfh8373y4hdi3ewfhbg87ezfyhq38yhiafha83oq
    issuer: http://localhost:8080
    expiration: 7

cloudinary:
  name: dqzwh7zvo
  apikey: 129334444479336
  secret: Lk1CRVD-DmLiCDdyNVQUNwqsmgA

springdoc:
  show-oauth2-endpoints: true
  pre-loading-enabled: true
  swagger-ui:
    path: /
    try-it-out-enabled: false
    operations-sorter: alpha
    syntax-highlight:
      activated: true
      theme: nord