spring:
  profiles:
    active:
    - dev
    - stage
    - prod
    default: default
  application:
    name: app-doc-sach
  datasource:
    url: jdbc:mysql://localhost:3306/appdocsach?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: appdocsach
    password: password
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      client-type: lettuce
      connect-timeout: 1000ms
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 558750477314-gsp55lnnjuj7ki5qint3epkr7p8s5dlj.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          github:
            client-id: Iv1.99344991fefa2587
            client-secret: 9cb9852fe6202faffbe10e785e88e1a6fa6b8fa9
      
# Cố định port
server:
  port: 8080

# Ghi log đẹp hơn
logging:
  charset:
    console: UTF-8
  pattern:
    dateformat: yy-MM-dd HH:mm

# cấu hình JWT
application:
  defaultAvatar: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dreamstime.com%2Fdefault-avatar-profile-icon-default-avatar-profile-icon-grey-photo-placeholder-illustrations-vectors-image105356006&psig=AOvVaw3u6LJZpu4Ou6VrRr9uVRQj&ust=1721481293919000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLiHltqXs4cDFQAAAAAdAAAAABAJ
  cron:
    clear-refresh-token-db: '* * */5 * * ?' # 5 ngày / lần
  auth:
    disable-duration: 30d
    jwt:
      secret: randomStringToMakeSecretKeyFdsksdnkzvk2oejaofcjewfr4ieoru39wjfmsfddshgvndkjfnakhdhiaukrfhqiauyh98atfh8373y4hdi3ewfhbg87ezfyhq38yhiafha83oq
      issuer: http://localhost:8080
      expirationMin: 40
    refresh:
      expirationDay: 7
      duration-to-delete: 15d

cloudinary:
  name: dqzwh7zvo
  apikey: 129334444479336
  secret: Lk1CRVD-DmLiCDdyNVQUNwqsmgA

springdoc:
  api-docs:
    enabled: false
  # show-oauth2-endpoints: true
  # pre-loading-enabled: false
  # swagger-ui:
  #   path: /
  #   try-it-out-enabled: false
  #   operations-sorter: alpha